name: dbus_secrets
description: A lightweight Dart package for securely storing and retrieving secrets using the Linux Secret Service API via D-Bus.
version: 0.0.1
repository: https://github.com/akshaybabloo/dbus_secrets
homepage: https://github.com/akshaybabloo/dbus_secrets
issue_tracker: https://github.com/akshaybabloo/dbus_secrets/issues

keywords:
  - dbus
  - secrets
  - keyring
  - password
  - security
  - linux

environment:
  sdk: ^3.7.2

platforms:
  linux:

dependencies:
  dbus: ^0.7.11

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
